---
title: "Adverse Events after Adjuvent Chemotherapy for Breast Cancer"
author: "Benjamin Chan"
date: "October 10, 2015"
output: html_document
---

# Background

See [README.md](https://github.com/benjamin-chan/AEAfterBreastCaACT).


# Preliminaries

1. Load [`devtools`](https://github.com/hadley/devtools)
1. Source the [`loadPkg`](https://gist.github.com/benjamin-chan/3b59313e8347fffea425) function
1. Load packages
1. Source the [`makeMetadata`](https://gist.github.com/benjamin-chan/091209ab4eee1f171540) function
1. Start the job timer

```{r, echo=FALSE}
if (!require(devtools)) {install.packages("devtools", dependencies=TRUE)}
library(devtools)
source_gist("https://gist.github.com/benjamin-chan/3b59313e8347fffea425")
loadPkg("data.table")
loadPkg("openxlsx")
# loadPkg("reshape2")
# loadPkg("metafor")
# loadPkg("R2jags")
# loadPkg("Rcpp")
# loadPkg("dplyr")
# loadPkg("ggplot2")
# loadPkg("ggmcmc")
source_gist("https://gist.github.com/benjamin-chan/091209ab4eee1f171540")
.timeStart <- Sys.time()
```


# Script sequence

**Need sequence of scripts**


# Session info

```{r, echo=FALSE}
source_gist("https://gist.github.com/benjamin-chan/80149dd4cdb16b2760ec")
```
