# Meta-analysis

```{r}
f <- "AllStudies.RData"
load(f, verbose=TRUE)
metadata
```

```{r}
D[, .N, .(author, monthsPostTx)][order(author, monthsPostTx)]
DPre  <- D[monthsPostTx == 0]
DPre [, .N, .(author, monthsPostTx)][order(author, monthsPostTx)]
DPost <- D[12 <= monthsPostTx]
DPost[, .N, .(author, monthsPostTx)][order(author, monthsPostTx)]
key <- c("author", "cognitiveDomain", "cognitiveTest", "isTimed", "scoreType")
setkeyv(DPre , key)
setkeyv(DPost, key)
D <- merge(DPre, DPost, suffixes=c("Pre", "Post"))
```

```{r}
D <- D[, diffMean := meanPost - meanPre]
D <- D[isTimed == TRUE, diffMean := -diffMean]
D <- D[,
       `:=` (sdPooled = sqrt((((nPre - 1) * (sdPre ^ 2)) +
                                ((nPost - 1) * (sdPost ^ 2))) /
                               (nPre + nPost - 2)))]
D <- D[,
       `:=` (cohenD = diffMean / sdPooled)]
D <- D[,
       `:=` (hedgesG = cohenD * (1 - (3 / ((4 * nPre + nPost) - 9))))]
D <- D[,
       `:=` (var1 = (nPre + nPost) / (nPre * nPost),
             var2 = hedgesG ^ 2 / (2 * (nPre + nPost)))]
D <- D[,
       `:=` (variance = var1 + var2)]
D <- D[,
       `:=` (se = sqrt(variance),
             weightFE = 1 / variance)]
D <- D[,
       `:=` (effSizeWeightedFE = weightFE * hedgesG)]
# D <- D[, weightRE := 1 / (variance + randomEffect)]
# D <- D[, effSizeWeightedRE := weightRE * hedgesG]
```

```{r}
D[, .(mean(effSizeWeightedFE), min(effSizeWeightedFE), max(effSizeWeightedFE)), scoreType]
```

Calculate fixed effects statisitcs.

```{r}
DFixed <- D[,
            .(df = .N,
              sumWeights = sum(weightFE),
              effSize = sum(effSizeWeightedFE) / sum(weightFE),
              se = sqrt(1 / sum(weightFE)),
              sumEffSizeWeighted = sum(effSizeWeightedFE),
              ssEffSizeWeighted = sum(weightFE * hedgesG ^ 2),
              ssWeights = sum(weightFE ^ 2)),
            .(cognitiveDomain)]
DFixed <- DFixed[,
                 `:=` (z = effSize / se,
                       lowerCI = effSize + qnorm(0.025) * se,
                       upperCI = effSize + qnorm(0.975) * se,
                       Q = ssEffSizeWeighted - (sumEffSizeWeighted ^ 2 / sumWeights),
                       criticalValue = qchisq(0.05, df, lower.tail=FALSE))]
DFixed <- DFixed[,
                 `:=` (pvalue = pchisq(Q, df, lower.tail=FALSE),
                       Isq = 100 * ((Q - df) / Q))]
show(DFixed)
```

Save working data tables to file.

```{r}
metadata <- makeMetadata(DFixed)
f <- "FixedEffects.RData"
save(DFixed, metadata, file=f)
message(sprintf("%s saved on: %s\nFile size: %s KB", 
                f,
                file.mtime(f),
                file.size(f) / 1e3))
```
